import { initializeAboutCompany } from "./about/about-company.js";
import { initializeAboutPhilosophy } from "./about/about-philosophy.js";
import { initializeAboutStaff } from "./about/about-staff.js";
import { initializeAboutStaffSlider } from "./about/staff-slider.js";
import { initializeEntryButton } from "./component/entry-button.js";
import { initializeHamburgerMenu } from "./component/hamburger-menu.js";
import { initializeHeaderBackgroundToggle } from "./component/header-background-toggle.js";
import { initializePageKv } from "./component/page-kv.js";
import { initializeContactForm } from "./contact/contact-form.js";
import { initializeNewsArchive } from "./news/news-archive.js";
import { initializeCultureGallery } from "./recruit/gallery-slider.js";
import { initializeRecruitBenefit } from "./recruit/recruit-benefit.js";
import { initializeRecruitPosition } from "./recruit/recruit-position.js";
import { initializeServiceCase } from "./service/service-case.js";
import { initializeServiceDetail } from "./service/service-detail.js";
import { initializeScrollBtn } from "./top/scroll-btn.js";
import { initializeTopAbout } from "./top/top-about.js";
import { initializeTopKvText } from "./top/top-kv-text.js";
import { initializeTopNews } from "./top/top-news.js";
import { initializeTopRecruit } from "./top/top-recruit.js";
import { initializeTopService } from "./top/top-service.js";

// 全ての初期化を実行
initializeHamburgerMenu();
initializeHeaderBackgroundToggle();
initializePageKv();
initializeScrollBtn();
initializeEntryButton();
initializeTopAbout();
initializeTopKvText();
initializeTopNews();
initializeTopRecruit();
initializeTopService();
initializeAboutPhilosophy();
initializeAboutStaffSlider();
initializeAboutCompany();
initializeAboutStaff();
initializeServiceDetail();
initializeServiceCase();
initializeNewsArchive();
initializeRecruitPosition();
initializeRecruitBenefit();
initializeCultureGallery();
initializeContactForm();
